# -*- coding: utf-8 -*-
"""LinearAlgebra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11FhutTkudBbTFWeT9HeCDO4EgI8P8-fX

# Linear Algebra is a field of mathematics that is universally agreed to be a prerequisite to a deeper understanding of machine learning.

1. Linear algebra is the mathematics of data
2. Linear algebra has had a marked impact on the field of statistics
3. Linear algebra underlies many practical mathematical tools, such as Fourier series and computer graphics.
"""

